### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by buraktamturk** [simolus3/f_grecaptcha#1]
I would like to port this library to iOS (using web tokens) using this library: https://github.com/fjcaetano/ReCaptcha

This library accomplish this with WebViews so the user will need to apply for two keys, one for Android and one for iOS (actually, web).

If I would to submit a PR, will you merge it or is it not a goal for this project?

**Comment by simolus3** [comment]
I would love to merge a pull request enabling iOS support, thank you for considering spending your time on this! 
Given that reCaptcha doesn't natively support iOS, making the user acquire two keys (as a bit of a hack) seems reasonable.

**Comment by ask007learning** [comment]
@buraktamturk  Any updates on this ? Flutter IOS recaptcha would be very helpful. Currently there are none available.

**Comment by ebeem** [comment]
I think this request is very reasonable

**Comment by christianwico** [comment]
Is anyone even working on this?
