### ISSUE TITLE
PlatformException(f_grecaptcha, Verification using reCaptcha has failed, null)

### ISSUE THREAD

**Issue by taslimR** [simolus3/f_grecaptcha#4]
**There is no problem with the internet, but still getting same issue**

W/System.err(16290): com.google.android.gms.common.api.ApiException: 12013: Invalid Package Name for App
W/System.err(16290): 	at com.google.android.gms.common.internal.zzb.zzy(Unknown Source:14)
W/System.err(16290): 	at com.google.android.gms.common.internal.zzbk.zzz(Unknown Source:0)
W/System.err(16290): 	at com.google.android.gms.common.internal.zzbl.zzr(Unknown Source:32)
W/System.err(16290): 	at com.google.android.gms.common.api.internal.BasePendingResult.zzc(Unknown Source:81)
W/System.err(16290): 	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(Unknown Source:41)
W/System.err(16290): 	at com.google.android.gms.internal.zzcwk.zza(Unknown Source:7)
W/System.err(16290): 	at com.google.android.gms.internal.zzcvw.onTransact(Unknown Source:101)
W/System.err(16290): 	at android.os.Binder.execTransact(Binder.java:697)
I/flutter (16290): Could not verify:
[38;5;244mI/flutter (16290): PlatformException(f_grecaptcha, Verification using reCaptcha has failed, null) at #0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244mI/flutter (16290): #1      MethodChannel._invokeMethod[39;49m
I/flutter (16290): <asynchronous suspension>
[38;5;244mI/flutter (16290): #2      MethodChannel.invokeMethod[39;49m
[38;5;248mI/flutter (16290): #3      FGrecaptcha.verifyWithRecaptcha[39;49m
I/flutter (16290): <asynchronous suspension>
[38;5;248mI/flutter (16290): #4      _MyAppState._startVerification[39;49m
[38;5;244mI/flutter (16290): #5      _InkResponseState._handleTap[39;49m
[38;5;244mI/flutter (16290): #6      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244mI/flutter (16290): #7      GestureRecognizer.invokeCallback[39;49m
[38;5;244mI/flutter (16290): #8      TapGestureRecognizer.handleTapUp[39;49m
I/flutter (16290): #9      BaseTapGestureRecognizer

![](https://images.guru/images/2020/07/26/QLU7E.png)

**Comment by daadu** [comment]
The log says `Invalid Package Name for App`.

Check in admin panel if you have entered (correctly) "package name / signature" of the app, it is mandatory, as mentioned in README.
